messages:
  staff:
    chat: "&7(&9StaffChat&7) -> &b %player% &7-> &a%message%"
  other:
    noConsole: "&cNo console command."
    noPermission: "&cYou do not have permissions to do this, please contact an administrator if you think it is an error."